/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutAccountImport } from './routes/_layout.account'
import { Route as LayoutRecipesIndexImport } from './routes/_layout.recipes.index'
import { Route as LayoutCanonicalIngredientsIndexImport } from './routes/_layout.canonical-ingredients.index'
import { Route as LayoutRecipesNewImport } from './routes/_layout.recipes.new'
import { Route as LayoutRecipesRecipeIdImport } from './routes/_layout.recipes.$recipeId'
import { Route as LayoutCanonicalIngredientsNewImport } from './routes/_layout.canonical-ingredients.new'
import { Route as LayoutRecipesRecipeIdEditImport } from './routes/_layout.recipes_.$recipeId.edit'
import { Route as LayoutCanonicalIngredientsCanonicalIngredientIdEditImport } from './routes/_layout.canonical-ingredients_.$canonicalIngredientId.edit'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAccountRoute = LayoutAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRecipesIndexRoute = LayoutRecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCanonicalIngredientsIndexRoute =
  LayoutCanonicalIngredientsIndexImport.update({
    id: '/canonical-ingredients/',
    path: '/canonical-ingredients/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutRecipesNewRoute = LayoutRecipesNewImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRecipesRecipeIdRoute = LayoutRecipesRecipeIdImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCanonicalIngredientsNewRoute =
  LayoutCanonicalIngredientsNewImport.update({
    id: '/canonical-ingredients/new',
    path: '/canonical-ingredients/new',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutRecipesRecipeIdEditRoute = LayoutRecipesRecipeIdEditImport.update({
  id: '/recipes_/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute =
  LayoutCanonicalIngredientsCanonicalIngredientIdEditImport.update({
    id: '/canonical-ingredients_/$canonicalIngredientId/edit',
    path: '/canonical-ingredients/$canonicalIngredientId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/_layout/account': {
      id: '/_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/canonical-ingredients/new': {
      id: '/_layout/canonical-ingredients/new'
      path: '/canonical-ingredients/new'
      fullPath: '/canonical-ingredients/new'
      preLoaderRoute: typeof LayoutCanonicalIngredientsNewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/recipes/$recipeId': {
      id: '/_layout/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof LayoutRecipesRecipeIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/recipes/new': {
      id: '/_layout/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof LayoutRecipesNewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/canonical-ingredients/': {
      id: '/_layout/canonical-ingredients/'
      path: '/canonical-ingredients'
      fullPath: '/canonical-ingredients'
      preLoaderRoute: typeof LayoutCanonicalIngredientsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/recipes/': {
      id: '/_layout/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof LayoutRecipesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/canonical-ingredients_/$canonicalIngredientId/edit': {
      id: '/_layout/canonical-ingredients_/$canonicalIngredientId/edit'
      path: '/canonical-ingredients/$canonicalIngredientId/edit'
      fullPath: '/canonical-ingredients/$canonicalIngredientId/edit'
      preLoaderRoute: typeof LayoutCanonicalIngredientsCanonicalIngredientIdEditImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/recipes_/$recipeId/edit': {
      id: '/_layout/recipes_/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof LayoutRecipesRecipeIdEditImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAccountRoute: typeof LayoutAccountRoute
  LayoutCanonicalIngredientsNewRoute: typeof LayoutCanonicalIngredientsNewRoute
  LayoutRecipesRecipeIdRoute: typeof LayoutRecipesRecipeIdRoute
  LayoutRecipesNewRoute: typeof LayoutRecipesNewRoute
  LayoutCanonicalIngredientsIndexRoute: typeof LayoutCanonicalIngredientsIndexRoute
  LayoutRecipesIndexRoute: typeof LayoutRecipesIndexRoute
  LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute: typeof LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute
  LayoutRecipesRecipeIdEditRoute: typeof LayoutRecipesRecipeIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountRoute: LayoutAccountRoute,
  LayoutCanonicalIngredientsNewRoute: LayoutCanonicalIngredientsNewRoute,
  LayoutRecipesRecipeIdRoute: LayoutRecipesRecipeIdRoute,
  LayoutRecipesNewRoute: LayoutRecipesNewRoute,
  LayoutCanonicalIngredientsIndexRoute: LayoutCanonicalIngredientsIndexRoute,
  LayoutRecipesIndexRoute: LayoutRecipesIndexRoute,
  LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute:
    LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute,
  LayoutRecipesRecipeIdEditRoute: LayoutRecipesRecipeIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof LayoutAccountRoute
  '/canonical-ingredients/new': typeof LayoutCanonicalIngredientsNewRoute
  '/recipes/$recipeId': typeof LayoutRecipesRecipeIdRoute
  '/recipes/new': typeof LayoutRecipesNewRoute
  '/canonical-ingredients': typeof LayoutCanonicalIngredientsIndexRoute
  '/recipes': typeof LayoutRecipesIndexRoute
  '/canonical-ingredients/$canonicalIngredientId/edit': typeof LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute
  '/recipes/$recipeId/edit': typeof LayoutRecipesRecipeIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof LayoutAccountRoute
  '/canonical-ingredients/new': typeof LayoutCanonicalIngredientsNewRoute
  '/recipes/$recipeId': typeof LayoutRecipesRecipeIdRoute
  '/recipes/new': typeof LayoutRecipesNewRoute
  '/canonical-ingredients': typeof LayoutCanonicalIngredientsIndexRoute
  '/recipes': typeof LayoutRecipesIndexRoute
  '/canonical-ingredients/$canonicalIngredientId/edit': typeof LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute
  '/recipes/$recipeId/edit': typeof LayoutRecipesRecipeIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_layout/account': typeof LayoutAccountRoute
  '/_layout/canonical-ingredients/new': typeof LayoutCanonicalIngredientsNewRoute
  '/_layout/recipes/$recipeId': typeof LayoutRecipesRecipeIdRoute
  '/_layout/recipes/new': typeof LayoutRecipesNewRoute
  '/_layout/canonical-ingredients/': typeof LayoutCanonicalIngredientsIndexRoute
  '/_layout/recipes/': typeof LayoutRecipesIndexRoute
  '/_layout/canonical-ingredients_/$canonicalIngredientId/edit': typeof LayoutCanonicalIngredientsCanonicalIngredientIdEditRoute
  '/_layout/recipes_/$recipeId/edit': typeof LayoutRecipesRecipeIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/canonical-ingredients/new'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/canonical-ingredients'
    | '/recipes'
    | '/canonical-ingredients/$canonicalIngredientId/edit'
    | '/recipes/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/canonical-ingredients/new'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/canonical-ingredients'
    | '/recipes'
    | '/canonical-ingredients/$canonicalIngredientId/edit'
    | '/recipes/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/sign-in'
    | '/sign-up'
    | '/_layout/account'
    | '/_layout/canonical-ingredients/new'
    | '/_layout/recipes/$recipeId'
    | '/_layout/recipes/new'
    | '/_layout/canonical-ingredients/'
    | '/_layout/recipes/'
    | '/_layout/canonical-ingredients_/$canonicalIngredientId/edit'
    | '/_layout/recipes_/$recipeId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/sign-in",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/account",
        "/_layout/canonical-ingredients/new",
        "/_layout/recipes/$recipeId",
        "/_layout/recipes/new",
        "/_layout/canonical-ingredients/",
        "/_layout/recipes/",
        "/_layout/canonical-ingredients_/$canonicalIngredientId/edit",
        "/_layout/recipes_/$recipeId/edit"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/_layout/account": {
      "filePath": "_layout.account.tsx",
      "parent": "/_layout"
    },
    "/_layout/canonical-ingredients/new": {
      "filePath": "_layout.canonical-ingredients.new.tsx",
      "parent": "/_layout"
    },
    "/_layout/recipes/$recipeId": {
      "filePath": "_layout.recipes.$recipeId.tsx",
      "parent": "/_layout"
    },
    "/_layout/recipes/new": {
      "filePath": "_layout.recipes.new.tsx",
      "parent": "/_layout"
    },
    "/_layout/canonical-ingredients/": {
      "filePath": "_layout.canonical-ingredients.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/recipes/": {
      "filePath": "_layout.recipes.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/canonical-ingredients_/$canonicalIngredientId/edit": {
      "filePath": "_layout.canonical-ingredients_.$canonicalIngredientId.edit.tsx",
      "parent": "/_layout"
    },
    "/_layout/recipes_/$recipeId/edit": {
      "filePath": "_layout.recipes_.$recipeId.edit.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
