name: 'pangea-recipes'

services:
  postgres:
    container_name: postgres
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pangearecipes
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_is_ready:
    image: postgres
    depends_on:
      postgres:
        condition: service_healthy

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - '3000:3000'

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/api.Dockerfile
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ./apps/api/.env
    environment:
      - PORT=3001
      - NODE_ENV=production

volumes:
  postgres-data:
