version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    networks:
      - hr_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - hr_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  hr_network:
    external: true
