packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - esbuild
  - playwright-chromium
  - prisma
  - sharp
  - vue-demi

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - '@tanstack/*'
