packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@sentry-internal/node-cpu-profiler': false
  core-js: false
  esbuild: false
  playwright-chromium: true
  prisma: false
  protobufjs: false
  sharp: false
  vue-demi: false

minimumReleaseAge: 720
