packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@parcel/watcher'
  - esbuild
  - prisma
  - sharp
  - vue-demi

minimumReleaseAge: 720

onlyBuiltDependencies:
  - '@sentry-internal/node-cpu-profiler'
  - playwright-chromium
