packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': false
  '@sentry/node-cpu-profiler': false
  esbuild: false
  playwright-chromium: true
  prisma: false
  sharp: false
  vue-demi: false

minimumReleaseAge: 720
